export const TASK_NAME_OPTIONS = [
  "Pano picotado",
  "Borracha",
  "Raspador",
  "Fita de demarcação",
  "Bin de entrada de célula NDC",
  "Bin de saída de célula NDC",
  "BIN da Stringer",
  "Limpeza Painel Golden para Amazônia",
  "Estação de ferro de solda",
  "Borrifador",
  "Testador de Solda Fria",
  "Máquina manual de arqueamento",
  "Caneta de fluxo",
  "Tirinha Auxiliar de Fita de Alta Temperatura",
  "Gabarito Célula Borda",
  "Robô aplicador de cola",
  "Bico separador de teste, cola de envase",
  "Gabarito raspador de cola",
  "Scanner",
  "Alicate de corte",
  "Assistente de solda",
  "Transpaleteira",
  "Aspirador",
  "Escova de Nylon",
  "Escova de latão",
  "Dispositivo passa ou não passa",
  "Polo de aferição Termômetro digital",
  "Base de aquecimento (Heater)",
  "Cartão serial Processo",
  "Gabarito de referência / Nivelador",
  "Scanners Keyence SR-1000 1D/2D",
  "Lâmina",
  "Pão-Duro",
  "Limpeza Climatizador",
  "Limpeza Ar-condicionado",
  "Gabarito de Teste",
  "Teste Painel Golden para Amazônia",
  "Painel para teste de falhas",
  "Gabarito de referência de colagem",
  "Ferramenta de Aperto Manual",
  "Carrinho",
  "Impressora",
  "Bancada",
  "Bico de Ar",
  "Balança",
  "Escala",
  "Estilete",
  "Trena",
  "Tesoura",
  "Paquimetro",
  "Empilhadeira manual",
  "Empilhadeira elétrica",
  "Carrinho transportador de tambor",
  "Calha string",
  "Caixa Bin",
  "Caixa Bin Nº7",
  "Espátula",
  "Funil",
  "Manta de Teflon",
  "Isolante térmico",
  "Máquina de fita",
  "Termômetro digital",
  "Pinça",
  "Manipulador de string",
  "Frasco de fluxo",
  "Gabarito de montagem manual Reparo OFF",
  "Ficha de defeito",
  "Lupa de medição",
  "Critério de Aceitabilidade de Inspeção Visual",
  "Lista de códigos de falha",
  "Gabarito de Dimensão de Defeitos",
  "Caneta e etiquetas de identificação",
  "Nivelador",
  "Calibre",
  "Chave inglesa",
  "Assistente de solda metálico",
  "Gabarito de alinhamento de caixas de junção",
  "Alicate bomba d'agua",
  "Testo Saveris 2H1",
  "Climatizador",
  "Ar-condicionado",
  "Pistola aplicadora de cola 1527",
  "Marreta",
  "Dispensador de fita",
  "Espátula de Feltro",
  "Escada cogumelo",
]

export const WORK_STATION_OPTIONS = [
  "Aparadora de backsheet",
  "Aparadora de encapsulante traseiro",
  "Aplicadora de cola de envase",
  "Aplicação Etiqueta Inmetro",
  "Aplicação Etiqueta de Especificação",
  "Aplicação da serial number",
  "Auto edge trimming",
  "Auto framing",
  "Auto label",
  "Auto soldering",
  "Autobussing",
  "Carregadora de vidro frontal",
  "Dobra de Barramento",
  "EL OFF",
  "EL test pré laminação",
  "EL teste 3",
  "EVA adicional",
  "Etiquetadora de modulo",
  "Flash test",
  "Hipot",
  "Inspeção 90 Graus",
  "Inspeção EL String",
  "Inspeção de solda caixa de junção e limpeza de frame",
  "Inspeção final 180º",
  "Laminadora",
  "Layup automático (buffer)",
  "Limpeza de painel lado frontal",
  "Montagem da caixa de junção",
  "Montagem manual de módulos",
  "Montagem tampa da caixa de junção e inserção de dispositivo de teste",
  "NDC",
  "Paletizadora seletora",
  "Reparo OFF",
  "Reparo ON",
  "Reparo de painel acabado",
  "Sala de cura",
  "Serial Traseiro",
  "Stringer",
  "Vidro traseiro",
]
